#!/bin/sh CommandsUsers.sh
echo "#  #!/bin/sh CommandsUsers.sh   #";
echo "# ===  === #";
echo "# === START ===  #";
echo "# RM(1) User Commands RM(1)  #";
echo "# ===  === #";
echo "# NAME  #";
echo "# rm - remove files or directories  #";
echo "# ===  === #";
echo "# SYNOPSIS  #";
echo "# rm [OPTION]... FILE...  #";
echo "# ===  === #";
echo "# DESCRIPTION  #";
echo "# This manual page documents the GNU version of rm. rm removes each specified file. By default, it does not remove directories.  #";
echo "# ===  === #";
echo "# If a file is unwritable, the standard input is a tty, and the -f or --force option is not given, rm prompts the user for whether to remove the file. If the response is  #";
echo "# not affirmative, the file is skipped.  #";
echo "# ===  === #";
echo "# OPTIONS  #";
echo "# Remove (unlink) the FILE(s).  #";
echo "# ===  === #";
echo "# -f, --force  #";
echo "# ignore nonexistent files, never prompt  #";
echo "# ===  === #";
echo "# -i, --interactive  #";
echo "# prompt before any removal  #";
echo "# ===  === #";
echo "# --no-preserve-root do not treat ‘/’ specially (the default)  #";
echo "# ===  === #";
echo "# --preserve-root  #";
echo "# fail to operate recursively on ‘/’  #";
echo "# ===  === #";
echo "# -r, -R, --recursive  #";
echo "# remove directories and their contents recursively  #";
echo "# ===  === #";
echo "# -v, --verbose  #";
echo "# explain what is being done  #";
echo "# ===  === #";
echo "# --help display this help and exit  #";
echo "# ===  === #";
echo "# --version  #";
echo "# output version information and exit  #";
echo "# ===  === #";
echo "# By default, rm does not remove directories.Use the --recursive(-r or -R)option to remove each listed directory, too, along with all of its contents.  #";
echo "# ===  === #";
echo "# To remove a file whose name starts with a ‘-’, for example ‘-foo’, use one of these commands:  #";
echo "# ===  === #";
echo "# rm -- -foo  #";
echo "# ===  === #";
echo "# rm ./-foo  #";
echo "# ===  === #";
echo "# Note that if you use rm to remove a file, it is usually possible to recover the contents of that file. If you want more assurance that the contents are truly unrecov-  #";
echo "# erable, consider using shred.  #";
echo "# === END ===  #";
echo "# ===  === #";