alias gs='git status '
alias ga='git add .'
alias gs='git commit -m "File edit or ... add new file" '
alias gb='git branch '
alias gps='git push '
alias gpu='git pull '
alias gs='git status '
alias gd='git diff '
alias gco='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '

alias gacpp='git status;git add .;git commit -m "Add file...";git push;git pull '
